<?php

namespace Sunaoka\RsyncUtils\Tests;

use PHPUnit\Framework\TestCase;
use Sunaoka\RsyncUtils\ItemizeChangesParser;

class ItemizeChangesParserTest extends TestCase
{
    public function test_parse(): void
    {
        $data = <<<DATA
        IO error encountered -- skipping file deletion
        cannot delete mount point: foo
        cannot delete non-empty directory: foo
        copying unsafe symlink "foo" -> "bar"
        not creating new directory "foo"
        skipping non-regular file "tty0"
        symlink has no referent: "foo"
        <f+++++++++ created file 1
        >f+++++++++ created file 2
        cd+++++++++ created directory/
        hf+++++++++ created => hardlink
        cL+++++++++ created -> symlink
        >fcstpog.ax updated file
        .d..t...... updated directory/
        .f..t...... updated symlink
        hf.st...... updated => hardlink
        *deleting   deleted file
        *deleting   deleted directory/
        *deleting   deleted hardlink
        *deleting   deleted symlink
        <f+++++++ created file 1
        >f+++++++ created file 2
        cd+++++++ created directory/
        hf+++++++ created => hardlink
        cL+++++++ created -> symlink
        >fcstpog. updated file
        .d..t.... updated directory/
        .f..t.... updated symlink
        hf.st.... updated => hardlink
        *deleting deleted file
        *deleting deleted directory/
        *deleting deleted hardlink
        *deleting deleted symlink
        DATA;

        $parser = new ItemizeChangesParser();
        $results = $parser->parse($data);

        $expected = [
            [
                'path'        => 'created file 1',
                'type'        => 'created',
                'updateType'  => 'sent',
                'fileType'    => 'file',
                'checksum'    => false,
                'size'        => false,
                'timestamp'   => false,
                'permissions' => false,
                'owner'       => false,
                'group'       => false,
                'acl'         => false,
                'xattr'       => false,
                'message'     => null,
            ],
            [
                'path'        => 'created file 2',
                'type'        => 'created',
                'updateType'  => 'received',
                'fileType'    => 'file',
                'checksum'    => false,
                'size'        => false,
                'timestamp'   => false,
                'permissions' => false,
                'owner'       => false,
                'group'       => false,
                'acl'         => false,
                'xattr'       => false,
                'message'     => null,
            ],
            [
                'path'        => 'created directory/',
                'type'        => 'created',
                'updateType'  => 'changed',
                'fileType'    => 'directory',
                'checksum'    => false,
                'size'        => false,
                'timestamp'   => false,
                'permissions' => false,
                'owner'       => false,
                'group'       => false,
                'acl'         => false,
                'xattr'       => false,
                'message'     => null,
            ],
            [
                'path'        => 'created',
                'type'        => 'created',
                'updateType'  => 'hardlink',
                'fileType'    => 'file',
                'checksum'    => false,
                'size'        => false,
                'timestamp'   => false,
                'permissions' => false,
                'owner'       => false,
                'group'       => false,
                'acl'         => false,
                'xattr'       => false,
                'message'     => null,
            ],
            [
                'path'        => 'created',
                'type'        => 'created',
                'updateType'  => 'changed',
                'fileType'    => 'symlink',
                'checksum'    => false,
                'size'        => false,
                'timestamp'   => false,
                'permissions' => false,
                'owner'       => false,
                'group'       => false,
                'acl'         => false,
                'xattr'       => false,
                'message'     => null,
            ],
            [
                'path'        => 'updated file',
                'type'        => 'updated',
                'updateType'  => 'received',
                'fileType'    => 'file',
                'checksum'    => true,
                'size'        => true,
                'timestamp'   => true,
                'permissions' => true,
                'owner'       => true,
                'group'       => true,
                'acl'         => true,
                'xattr'       => true,
                'message'     => null,
            ],
            [
                'path'        => 'updated directory/',
                'type'        => 'updated',
                'updateType'  => 'unchanged',
                'fileType'    => 'directory',
                'checksum'    => false,
                'size'        => false,
                'timestamp'   => true,
                'permissions' => false,
                'owner'       => false,
                'group'       => false,
                'acl'         => false,
                'xattr'       => false,
                'message'     => null,
            ],
            [
                'path'        => 'updated symlink',
                'type'        => 'updated',
                'updateType'  => 'unchanged',
                'fileType'    => 'file',
                'checksum'    => false,
                'size'        => false,
                'timestamp'   => true,
                'permissions' => false,
                'owner'       => false,
                'group'       => false,
                'acl'         => false,
                'xattr'       => false,
                'message'     => null,
            ],
            [
                'path'        => 'updated',
                'type'        => 'updated',
                'updateType'  => 'hardlink',
                'fileType'    => 'file',
                'checksum'    => false,
                'size'        => true,
                'timestamp'   => true,
                'permissions' => false,
                'owner'       => false,
                'group'       => false,
                'acl'         => false,
                'xattr'       => false,
                'message'     => null,
            ],
            [
                'path'        => 'deleted file',
                'type'        => 'deleted',
                'updateType'  => 'deleting',
                'fileType'    => 'directory',
                'checksum'    => false,
                'size'        => false,
                'timestamp'   => false,
                'permissions' => false,
                'owner'       => false,
                'group'       => false,
                'acl'         => false,
                'xattr'       => false,
                'message'     => null,
            ],
            [
                'path'        => 'deleted directory/',
                'type'        => 'deleted',
                'updateType'  => 'deleting',
                'fileType'    => 'directory',
                'checksum'    => false,
                'size'        => false,
                'timestamp'   => false,
                'permissions' => false,
                'owner'       => false,
                'group'       => false,
                'acl'         => false,
                'xattr'       => false,
                'message'     => null,
            ],
            [
                'path'        => 'deleted hardlink',
                'type'        => 'deleted',
                'updateType'  => 'deleting',
                'fileType'    => 'directory',
                'checksum'    => false,
                'size'        => false,
                'timestamp'   => false,
                'permissions' => false,
                'owner'       => false,
                'group'       => false,
                'acl'         => false,
                'xattr'       => false,
                'message'     => null,
            ],
            [
                'path'        => 'deleted symlink',
                'type'        => 'deleted',
                'updateType'  => 'deleting',
                'fileType'    => 'directory',
                'checksum'    => false,
                'size'        => false,
                'timestamp'   => false,
                'permissions' => false,
                'owner'       => false,
                'group'       => false,
                'acl'         => false,
                'xattr'       => false,
                'message'     => null,
            ],
            [
                'path'        => 'created file 1',
                'type'        => 'created',
                'updateType'  => 'sent',
                'fileType'    => 'file',
                'checksum'    => false,
                'size'        => false,
                'timestamp'   => false,
                'permissions' => false,
                'owner'       => false,
                'group'       => false,
                'acl'         => false,
                'xattr'       => false,
                'message'     => null,
            ],
            [
                'path'        => 'created file 2',
                'type'        => 'created',
                'updateType'  => 'received',
                'fileType'    => 'file',
                'checksum'    => false,
                'size'        => false,
                'timestamp'   => false,
                'permissions' => false,
                'owner'       => false,
                'group'       => false,
                'acl'         => false,
                'xattr'       => false,
                'message'     => null,
            ],
            [
                'path'        => 'created directory/',
                'type'        => 'created',
                'updateType'  => 'changed',
                'fileType'    => 'directory',
                'checksum'    => false,
                'size'        => false,
                'timestamp'   => false,
                'permissions' => false,
                'owner'       => false,
                'group'       => false,
                'acl'         => false,
                'xattr'       => false,
                'message'     => null,
            ],
            [
                'path'        => 'created',
                'type'        => 'created',
                'updateType'  => 'hardlink',
                'fileType'    => 'file',
                'checksum'    => false,
                'size'        => false,
                'timestamp'   => false,
                'permissions' => false,
                'owner'       => false,
                'group'       => false,
                'acl'         => false,
                'xattr'       => false,
                'message'     => null,
            ],
            [
                'path'        => 'created',
                'type'        => 'created',
                'updateType'  => 'changed',
                'fileType'    => 'symlink',
                'checksum'    => false,
                'size'        => false,
                'timestamp'   => false,
                'permissions' => false,
                'owner'       => false,
                'group'       => false,
                'acl'         => false,
                'xattr'       => false,
                'message'     => null,
            ],
            [
                'path'        => 'updated file',
                'type'        => 'updated',
                'updateType'  => 'received',
                'fileType'    => 'file',
                'checksum'    => true,
                'size'        => true,
                'timestamp'   => true,
                'permissions' => true,
                'owner'       => true,
                'group'       => true,
                'acl'         => false,
                'xattr'       => false,
                'message'     => null,
            ],
            [
                'path'        => 'updated directory/',
                'type'        => 'updated',
                'updateType'  => 'unchanged',
                'fileType'    => 'directory',
                'checksum'    => false,
                'size'        => false,
                'timestamp'   => true,
                'permissions' => false,
                'owner'       => false,
                'group'       => false,
                'acl'         => false,
                'xattr'       => false,
                'message'     => null,
            ],
            [
                'path'        => 'updated symlink',
                'type'        => 'updated',
                'updateType'  => 'unchanged',
                'fileType'    => 'file',
                'checksum'    => false,
                'size'        => false,
                'timestamp'   => true,
                'permissions' => false,
                'owner'       => false,
                'group'       => false,
                'acl'         => false,
                'xattr'       => false,
                'message'     => null,
            ],
            [
                'path'        => 'updated',
                'type'        => 'updated',
                'updateType'  => 'hardlink',
                'fileType'    => 'file',
                'checksum'    => false,
                'size'        => true,
                'timestamp'   => true,
                'permissions' => false,
                'owner'       => false,
                'group'       => false,
                'acl'         => false,
                'xattr'       => false,
                'message'     => null,
            ],
            [
                'path'        => 'deleted file',
                'type'        => 'deleted',
                'updateType'  => 'deleting',
                'fileType'    => 'directory',
                'checksum'    => false,
                'size'        => false,
                'timestamp'   => false,
                'permissions' => false,
                'owner'       => false,
                'group'       => false,
                'acl'         => false,
                'xattr'       => false,
                'message'     => null,
            ],
            [
                'path'        => 'deleted directory/',
                'type'        => 'deleted',
                'updateType'  => 'deleting',
                'fileType'    => 'directory',
                'checksum'    => false,
                'size'        => false,
                'timestamp'   => false,
                'permissions' => false,
                'owner'       => false,
                'group'       => false,
                'acl'         => false,
                'xattr'       => false,
                'message'     => null,
            ],
            [
                'path'        => 'deleted hardlink',
                'type'        => 'deleted',
                'updateType'  => 'deleting',
                'fileType'    => 'directory',
                'checksum'    => false,
                'size'        => false,
                'timestamp'   => false,
                'permissions' => false,
                'owner'       => false,
                'group'       => false,
                'acl'         => false,
                'xattr'       => false,
                'message'     => null,
            ],
            [
                'path'        => 'deleted symlink',
                'type'        => 'deleted',
                'updateType'  => 'deleting',
                'fileType'    => 'directory',
                'checksum'    => false,
                'size'        => false,
                'timestamp'   => false,
                'permissions' => false,
                'owner'       => false,
                'group'       => false,
                'acl'         => false,
                'xattr'       => false,
                'message'     => null,
            ],
        ];

        $actual = array_map(static fn($file) => $file->toArray(), $results);

        self::assertSame($expected, $actual);
    }
}
